// Fable — the writer. All POST content is generated by Claude Fable 5 through here.
// One switch point: change the model or effort in this file and every generator follows.
//
// Calls the Anthropic Messages API over plain fetch (no SDK dependency, so it builds
// under any package manager). Needs ANTHROPIC_API_KEY in the environment (Railway) —
// if it's missing we throw a clear, human error instead of a cryptic one.

export const FABLE_MODEL = 'claude-fable-5'

const ANTHROPIC_URL = 'https://api.anthropic.com/v1/messages'
const ANTHROPIC_VERSION = '2023-06-01'

type Effort = 'low' | 'medium' | 'high'

type TextBlock = { type: string; text?: string }
type AnthropicResponse = {
  content?: TextBlock[]
  stop_reason?: string | null
  error?: { message?: string }
}

// Drop-in replacement for the old OpenAI `responses.create({ instructions, input })`
// → `output_text` shape. Returns the plain text Fable wrote.
//
// effort controls how hard Fable thinks: 'low' for quick single rewrites (fast,
// keeps route timeouts honest), 'medium' for batches. Fable's raw reasoning is
// never returned — we only read the text blocks.
export async function fableText(opts: {
  instructions: string
  input: string
  maxTokens?: number
  effort?: Effort
  imageUrl?: string
  imageUrls?: string[]
}): Promise<string> {
  const apiKey = process.env.ANTHROPIC_API_KEY
  if (!apiKey) {
    throw new Error('ANTHROPIC_API_KEY is not set — add it in Railway → Variables so Fable can write.')
  }

  // When images are attached (a photo, or sampled video frames), Fable actually
  // looks at them — the text goes alongside the image blocks in the same user turn.
  const images = [opts.imageUrl, ...(opts.imageUrls ?? [])].filter(Boolean) as string[]
  const userContent = images.length
    ? [
        ...images.map(url => ({ type: 'image', source: { type: 'url', url } })),
        { type: 'text', text: opts.input },
      ]
    : opts.input

  const res = await fetch(ANTHROPIC_URL, {
    method: 'POST',
    headers: {
      'content-type': 'application/json',
      'x-api-key': apiKey,
      'anthropic-version': ANTHROPIC_VERSION,
    },
    body: JSON.stringify({
      model: FABLE_MODEL,
      max_tokens: opts.maxTokens ?? 8000,
      system: opts.instructions,
      messages: [{ role: 'user', content: userContent }],
      output_config: { effort: opts.effort ?? 'medium' },
    }),
  })

  const data = (await res.json()) as AnthropicResponse

  if (!res.ok) {
    throw new Error(`Fable API error (${res.status}): ${data?.error?.message ?? 'unknown error'}`)
  }
  if (data.stop_reason === 'refusal') {
    throw new Error('Fable declined this request. Rephrase the prompt or the source note.')
  }

  return (data.content ?? [])
    .filter(b => b.type === 'text' && typeof b.text === 'string')
    .map(b => b.text as string)
    .join('')
    .trim()
}

// ── The Researcher — live web search with a heavyweight thinker ───────────────
// Uses Claude Opus 4.8 + the server-side web_search tool (Fable doesn't carry
// the search tool; Opus 4.8 is the intelligent reader/curator this job needs).
// Handles pause_turn (server tool loop limit) by resuming until done.
export async function researchWithWeb(opts: {
  instructions: string
  input: string
  maxTokens?: number
  maxSearches?: number
}): Promise<string> {
  const apiKey = process.env.ANTHROPIC_API_KEY
  if (!apiKey) {
    throw new Error('ANTHROPIC_API_KEY is not set — add it in Railway → Variables so the researcher can work.')
  }

  const headers = {
    'content-type': 'application/json',
    'x-api-key': apiKey,
    'anthropic-version': ANTHROPIC_VERSION,
  }

  let messages: Array<Record<string, unknown>> = [{ role: 'user', content: opts.input }]
  let final: AnthropicResponse | null = null

  // Resume across pause_turn up to 5 times (server-side search loop limit)
  for (let i = 0; i < 5; i++) {
    const res = await fetch(ANTHROPIC_URL, {
      method: 'POST',
      headers,
      body: JSON.stringify({
        model: 'claude-opus-4-8',
        max_tokens: opts.maxTokens ?? 8000,
        system: opts.instructions,
        thinking: { type: 'adaptive' },
        tools: [{ type: 'web_search_20260209', name: 'web_search', max_uses: opts.maxSearches ?? 8 }],
        messages,
      }),
    })
    const data = (await res.json()) as AnthropicResponse & { content?: Array<Record<string, unknown>> }
    if (!res.ok) {
      throw new Error(`Researcher API error (${res.status}): ${(data as AnthropicResponse)?.error?.message ?? 'unknown error'}`)
    }
    final = data as AnthropicResponse
    if (data.stop_reason !== 'pause_turn') break
    // Paused mid-search — echo the assistant turn back and let it resume
    messages = [...messages, { role: 'assistant', content: data.content }]
  }

  return ((final?.content ?? []) as TextBlock[])
    .filter(b => b.type === 'text' && typeof b.text === 'string')
    .map(b => b.text as string)
    .join('')
    .trim()
}
