// Fable — the writer. All POST content is generated by Claude Fable 5 through here.
// One switch point: change the model or effort in this file and every generator follows.
//
// Calls the Anthropic Messages API over plain fetch (no SDK dependency, so it builds
// under any package manager). Needs ANTHROPIC_API_KEY in the environment (Railway) —
// if it's missing we throw a clear, human error instead of a cryptic one.

export const FABLE_MODEL = 'claude-fable-5'

const ANTHROPIC_URL = 'https://api.anthropic.com/v1/messages'
const ANTHROPIC_VERSION = '2023-06-01'

type Effort = 'low' | 'medium' | 'high'

type TextBlock = { type: string; text?: string }
type AnthropicResponse = {
  content?: TextBlock[]
  stop_reason?: string | null
  error?: { message?: string }
}

// Drop-in replacement for the old OpenAI `responses.create({ instructions, input })`
// → `output_text` shape. Returns the plain text Fable wrote.
//
// effort controls how hard Fable thinks: 'low' for quick single rewrites (fast,
// keeps route timeouts honest), 'medium' for batches. Fable's raw reasoning is
// never returned — we only read the text blocks.
export async function fableText(opts: {
  instructions: string
  input: string
  maxTokens?: number
  effort?: Effort
  imageUrl?: string
  imageUrls?: string[]
}): Promise<string> {
  const apiKey = process.env.ANTHROPIC_API_KEY
  if (!apiKey) {
    throw new Error('ANTHROPIC_API_KEY is not set — add it in Railway → Variables so Fable can write.')
  }

  // When images are attached (a photo, or sampled video frames), Fable actually
  // looks at them — the text goes alongside the image blocks in the same user turn.
  const images = [opts.imageUrl, ...(opts.imageUrls ?? [])].filter(Boolean) as string[]
  const userContent = images.length
    ? [
        ...images.map(url => ({ type: 'image', source: { type: 'url', url } })),
        { type: 'text', text: opts.input },
      ]
    : opts.input

  const res = await fetch(ANTHROPIC_URL, {
    method: 'POST',
    headers: {
      'content-type': 'application/json',
      'x-api-key': apiKey,
      'anthropic-version': ANTHROPIC_VERSION,
    },
    body: JSON.stringify({
      model: FABLE_MODEL,
      max_tokens: opts.maxTokens ?? 8000,
      system: opts.instructions,
      messages: [{ role: 'user', content: userContent }],
      output_config: { effort: opts.effort ?? 'medium' },
    }),
  })

  const data = (await res.json()) as AnthropicResponse

  if (!res.ok) {
    throw new Error(`Fable API error (${res.status}): ${data?.error?.message ?? 'unknown error'}`)
  }
  if (data.stop_reason === 'refusal') {
    throw new Error('Fable declined this request. Rephrase the prompt or the source note.')
  }

  return (data.content ?? [])
    .filter(b => b.type === 'text' && typeof b.text === 'string')
    .map(b => b.text as string)
    .join('')
    .trim()
}
