import { NextRequest, NextResponse } from 'next/server'
import { getAllNotes, createNote, updateNote, deleteNote, logActivity } from '@/lib/db'

export const dynamic = 'force-dynamic'

// Auto-generated byproducts we don't surface in the Activity feed (too noisy).
const QUIET_TAGS = ['trends-source', 'river-research', 'transcript', 'episode-kit', 'deliverables', 'medium', 'newsletter']

export async function GET(req: NextRequest) {
  const params = new URL(req.url).searchParams
  const category = params.get('category') ?? undefined
  const search = params.get('search') ?? undefined
  return NextResponse.json(getAllNotes(category, search))
}

export async function POST(req: NextRequest) {
  const body = await req.json()
  const note = createNote(body)
  // Show it in the Activity feed so RISE visibly received what she submitted.
  if (!(note.tags ?? []).some(t => QUIET_TAGS.includes(t))) {
    const t = (note.title || 'Note').replace(/^[^\w]+/, '').trim()
    logActivity({ type: 'note', title: `Note saved: ${t}`.slice(0, 100), icon: note.source === 'rise' ? '🔬' : '📝', source: 'notes' })
  }
  return NextResponse.json(note)
}

export async function PATCH(req: NextRequest) {
  const body = await req.json()
  const { id, ...updates } = body
  if (!id) return NextResponse.json({ error: 'id required' }, { status: 400 })
  const result = updateNote(Number(id), updates)
  if (!result) return NextResponse.json({ error: 'not found' }, { status: 404 })
  return NextResponse.json(result)
}

export async function DELETE(req: NextRequest) {
  const id = new URL(req.url).searchParams.get('id')
  if (!id) return NextResponse.json({ error: 'id required' }, { status: 400 })
  deleteNote(Number(id))
  return NextResponse.json({ success: true })
}
