import { NextRequest, NextResponse } from 'next/server'
import { getAllContent, updateContent, getBrandAccount, getWatchContext, getAudienceContext } from '@/lib/db'
import { craftFor } from '@/lib/craft'
import { fableText } from '@/lib/fable'

export const dynamic = 'force-dynamic'
export const maxDuration = 300

// Bulk re-write existing posts through Claude Fable 5 — a few per request so each
// call stays under the timeout. Posts already re-done get the 'fable' tag so we
// never touch them twice; loop this endpoint until { remaining } hits 0.
// In-place: it overwrites the caption/on-screen/hashtags of each post.
export async function POST(req: NextRequest) {
  const body = await req.json().catch(() => ({}))
  const limit = Math.max(1, Math.min(5, Number(body.limit) || 3))

  const all = getAllContent()
  const pending = all.filter(c => !(c.tags ?? []).includes('fable'))
  const batch = pending.slice(0, limit)

  const done: number[] = []
  const failed: number[] = []

  for (const piece of batch) {
    const account = piece.account_id ? getBrandAccount(piece.account_id) : null
    const voice = account
      ? `ACCOUNT: ${account.handle} (${account.brand_name}) — ${account.topic}. Tone: ${account.tone}. ${account.offer ? `Offer: ${account.offer}.` : ''}\n${account.notes ? `NON-NEGOTIABLE RULES (obey exactly): ${account.notes}` : ''}`
      : 'VOICE: Mandi Beck — warm, direct, no fluff.'

    const prompt = `${voice}
${getWatchContext()}

${craftFor(piece.account_id)}

${getAudienceContext(account?.audience_id)}

Re-write this existing post in Fable's voice. Keep the same core idea, format, and intent, but make it land harder — sharper hook, more specific, real value. Do NOT invent facts about Mandi's life.

ORIGINAL:
Title: ${piece.title}
On-screen: ${piece.onscreen_text ?? ''}
Caption: ${piece.description ?? ''}

CONTENT AUDIT RULES: lead with HER (the reader's) problem/moment, 3-second cold-stranger test, comment-keyword CTA matching the account, no links in captions.

Return ONLY valid JSON: { "title": "...", "onscreen_text": "...", "caption": "full ready-to-post caption with CTA", "hashtags": "up to 5 hashtags space-separated" }`

    try {
      const output = await fableText({
        instructions: 'You are a master storyteller re-writing content to make people FEEL something. Show, never tell. Return only valid JSON.',
        input: prompt,
        maxTokens: 3000,
        effort: 'low',
      })
      const parsed = JSON.parse(output.match(/\{[\s\S]*\}/)![0])
      updateContent(piece.id, {
        title: parsed.title || piece.title,
        onscreen_text: parsed.onscreen_text ?? piece.onscreen_text,
        description: parsed.caption ?? piece.description,
        hashtags: parsed.hashtags ?? piece.hashtags,
        tags: [...(piece.tags ?? []), 'fable'],
      })
      done.push(piece.id)
    } catch {
      // Tag it so the loop moves on; it can be regenerated by hand later.
      updateContent(piece.id, { tags: [...(piece.tags ?? []), 'fable', 'fable-failed'] })
      failed.push(piece.id)
    }
  }

  const remaining = pending.length - batch.length
  return NextResponse.json({ processed: batch.length, done, failed, remaining, total: all.length })
}
