import { NextRequest, NextResponse } from 'next/server'
import { getAllNotes, updateNote } from '@/lib/db'
import type { Note } from '@/lib/db'

export const dynamic = 'force-dynamic'
export const maxDuration = 300

// DAILY AUTO-DRAFT — reads Mandi's RECENT own notes/ideas and runs each through the
// River (the sorting-hat: picks the best account, obeys the craft laws, writes a
// ready-for-approval post). Nothing publishes — everything lands as a card to
// approve in Accounts. Each note it drafts gets tagged 'auto-drafted' so it's never
// drafted twice.
//
// Trigger it daily by hitting:  /api/cron/draft-from-notes?key=YOUR_CRON_SECRET
// (set CRON_SECRET in Railway; if it's unset the endpoint still runs, unprotected.)

// Draft from BOTH Mandi's own notes AND RISE-generated IDEAS (research briefs, media
// stories, trend finds). Only skip things that aren't postable ideas: raw episode
// transcripts, finished episode kits, and already-finished drafts awaiting approval.
// Also skip 'river-research' and 'trends-source': those are auto-generated BYPRODUCTS
// (the River writes a research note every time it composes, and trend watchers drop
// source notes) — not ideas waiting to be drafted. They were flooding the queue and
// starving Mandi's actual hand-written ideas, so a note she leaves today never got
// drafted behind dozens of research digs. Her real ideas come first now.
const SKIP_TAGS = ['transcript', 'episode-kit', 'deliverables', 'needs-approval', 'medium', 'newsletter', 'substack', 'auto-drafted', 'river-research', 'trends-source']
// A DRAFTING QUEUE, not a snapshot: any idea you drop waits its turn and is drafted
// OLDEST-FIRST, so leftovers from a heavy day get picked up on the next run before
// newer ideas — nothing is lost. The window is just a safety cap so the ancient
// backlog never floods in; 30 days = ~12 M/W/F runs of runway per idea.
const WINDOW_DAYS = 30  // an un-drafted idea stays eligible for ~30 days
const MAX_IDEAS = 3     // cap IDEAS per run — each fans across the accounts it serves

// Is this a note worth drafting a post from? Includes her ideas, Commander-saved
// notes, AND RISE's own idea fodder (🔬 research, 📎 media stories, 📡 trends).
// Excludes only non-ideas: raw transcripts (📄), episode kits (🎙), finished deliverables.
function isDraftableIdea(n: Note): boolean {
  if (n.archived) return false
  const tags = n.tags ?? []
  if (SKIP_TAGS.some(t => tags.includes(t))) return false
  if (/transcript|deliverables|ep kit|episode kit/i.test(n.title || '')) return false
  if (/^\s*[📄🎙]/u.test(n.title || '')) return false   // skip raw transcript / episode kit only
  return (n.body || '').trim().length >= 40  // enough substance to build a post from
}

async function run(req: NextRequest) {
  const key = new URL(req.url).searchParams.get('key')
  const secret = process.env.CRON_SECRET
  if (secret && key !== secret) return NextResponse.json({ error: 'unauthorized' }, { status: 401 })

  // Call RISE's own routes on the internal loopback, NOT the public URL — Railway's
  // edge refuses a container looping back through its own public hostname.
  const base = `http://127.0.0.1:${process.env.PORT || 3000}`
  // Optional ?limit=N override (for a small/cheap test run); capped at MAX_IDEAS.
  const limitParam = Number(new URL(req.url).searchParams.get('limit'))
  const cap = Number.isFinite(limitParam) && limitParam > 0 ? Math.min(limitParam, MAX_IDEAS) : MAX_IDEAS
  const cutoff = Date.now() - WINDOW_DAYS * 86400000
  const candidates = getAllNotes()
    .filter(isDraftableIdea)
    .filter(n => new Date(n.created_at).getTime() >= cutoff)
    // NEWEST first — now that the research/trends flood is excluded, the pool is just
    // Mandi's real ideas, and she wants the notes she left TODAY to become posts, not
    // to wait behind a week-old backlog. Fresh ideas draft first.
    .sort((a, b) => new Date(b.created_at).getTime() - new Date(a.created_at).getTime())
    .slice(0, cap)

  // For ONE idea: SHRED it across accounts (Commander plan) → COMPOSE each placement.
  // Returns the posts it created (or a skip reason).
  const draftIdea = async (n: Note) => {
    try {
      const planRes = await fetch(`${base}/api/commander`, {
        method: 'POST', headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ mode: 'plan', input: `${n.title}\n\n${n.body}` }),
      })
      const plan = await planRes.json().catch(() => ({}))
      const shreds = Array.isArray(plan.shreds) ? plan.shreds : []
      if (!shreds.length) return { note: n.title, posts: [] as { id: number; handle: string }[], why: plan.error || 'nothing to place across accounts' }

      const compRes = await fetch(`${base}/api/commander`, {
        method: 'POST', headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ mode: 'compose', shreds }),
      })
      const comp = await compRes.json().catch(() => ({}))
      const posts = Array.isArray(comp.created) ? comp.created.map((c: { id: number; handle: string }) => ({ id: c.id, handle: c.handle })) : []
      if (posts.length) updateNote(n.id, { tags: [...(n.tags ?? []), 'auto-drafted'] })
      return { note: n.title, posts, why: posts.length ? undefined : (comp.error || 'compose produced nothing') }
    } catch (e) {
      return { note: n.title, posts: [] as { id: number; handle: string }[], why: e instanceof Error ? e.message : 'draft failed' }
    }
  }

  // Run the (≤3) ideas in PARALLEL so their composes overlap and the whole run fits
  // inside the 300s function limit — capped at 3 ideas, so peak concurrency stays low.
  const results = await Promise.all(candidates.map(draftIdea))
  const drafted = results.filter(r => r.posts.length)
  const skipped = results.filter(r => !r.posts.length).map(r => ({ note: r.note, why: r.why ?? 'skipped' }))
  const postCount = drafted.reduce((sum, r) => sum + r.posts.length, 0)

  return NextResponse.json({
    ran_at: new Date().toISOString(),
    ideas_considered: candidates.length,
    ideas_drafted: drafted.length,
    posts_created: postCount,
    drafted: drafted.map(r => ({ idea: r.note, posts: r.posts })),
    skipped,
    note: postCount ? `${postCount} posts across ${drafted.length} ideas — all in Accounts, ready to approve.` : 'No new ideas to draft today.',
  })
}

// GET (for simple cron pings) and POST both work.
export async function GET(req: NextRequest) { return run(req) }
export async function POST(req: NextRequest) { return run(req) }
